cURL "https://cse341-contacts-t3nz.onrender.com/"

cURL "https://cse341-contacts-t3nz.onrender.com/contacts"

cURL "https://cse341-contacts-t3nz.onrender.com/contacts/66285b5fe05dadece0f8ef5f"

cURL "https://cse341-contacts-t3nz.onrender.com/contacts/66285c39e05dadece0f8ef60"

cURL "https://cse341-contacts-t3nz.onrender.com/contacts/gender/m"

cURL "https://cse341-contacts-t3nz.onrender.com/contacts/gender/f"

